services:
  pgdatabase:
    image: 'postgres:13'
    container_name: 'pgdatabase'
    environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: user
     POSTGRES_DB: taxi_data
    volumes:
     - "./etl_postgres:/var/lib/postgresql/data:rw"
    ports:
     - "5432:5432"
    restart: 'always'
    networks:
     - 'airflow' 

networks:
  airflow:
    external:
      name: 'airflow_default' 